# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clock_review.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClockReview(object):
    def setupUi(self, ClockReview):
        ClockReview.setObjectName("ClockReview")
        ClockReview.resize(1207, 670)
        ClockReview.setStyleSheet("QMainWindow {\n"
"    background-color:rgb(250, 250, 250);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(ClockReview)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 32, 451, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setStyleSheet("QCalendarWidget QTableView {\n"
"    selection-background-color: #C1272D;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"#qt_calendar_navigationbar {\n"
"    background-color: #C1272D;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 550, 50, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 400, 60, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 510, 60, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 350, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1070, 0, 137, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(1548, 753))
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:18px;\n"
"    /*字体颜色为白色*/\n"
"    font-weight:bold;    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#C1272D;\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#9e1e24;\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#CD5257;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 450, 60, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(870, 620, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:17px;\n"
"    /*字体颜色为白色*/\n"
"    font-weight: bold;    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#C1272D;\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#9e1e24;\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#CD5257;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1, 0, 1208, 30))
        self.label_2.setStyleSheet("QWidget\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:18px;\n"
"    /*字体颜色为白色*/    \n"
"    font-weight:bold;\n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#C1272D;\n"
"\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(470, 30, 736, 570))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: rgb(225, 255, 254);\n"
"    font-size: 11px;\n"
"}")
        self.tableWidget_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setShowGrid(True)
        self.tableWidget_3.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_3.setRowCount(1)
        self.tableWidget_3.setColumnCount(13)
        self.tableWidget_3.setObjectName("tableWidget_3")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.verticalHeader().setStretchLastSection(False)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_8.setObjectName("label_8")
        self.textEdit_10 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_10.setGeometry(QtCore.QRect(80, 250, 70, 40))
        self.textEdit_10.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_10.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_10.setLineWidth(1)
        self.textEdit_10.setAcceptRichText(False)
        self.textEdit_10.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 300, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_9.setObjectName("label_9")
        self.textEdit_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_11.setGeometry(QtCore.QRect(80, 300, 70, 40))
        self.textEdit_11.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_11.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_11.setLineWidth(1)
        self.textEdit_11.setAcceptRichText(False)
        self.textEdit_11.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_12.setGeometry(QtCore.QRect(80, 350, 170, 40))
        self.textEdit_12.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_12.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_12.setLineWidth(1)
        self.textEdit_12.setAcceptRichText(False)
        self.textEdit_12.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_12.setObjectName("textEdit_12")
        self.textEdit_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_13.setGeometry(QtCore.QRect(80, 400, 170, 40))
        self.textEdit_13.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_13.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_13.setLineWidth(1)
        self.textEdit_13.setAcceptRichText(False)
        self.textEdit_13.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_13.setObjectName("textEdit_13")
        self.textEdit_14 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_14.setGeometry(QtCore.QRect(80, 450, 170, 40))
        self.textEdit_14.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_14.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_14.setLineWidth(1)
        self.textEdit_14.setAcceptRichText(False)
        self.textEdit_14.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_14.setObjectName("textEdit_14")
        self.textEdit_15 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_15.setGeometry(QtCore.QRect(80, 500, 170, 40))
        self.textEdit_15.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_15.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_15.setLineWidth(1)
        self.textEdit_15.setAcceptRichText(False)
        self.textEdit_15.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_15.setObjectName("textEdit_15")
        self.textEdit_16 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_16.setGeometry(QtCore.QRect(80, 550, 170, 40))
        self.textEdit_16.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_16.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_16.setLineWidth(1)
        self.textEdit_16.setAcceptRichText(False)
        self.textEdit_16.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_16.setObjectName("textEdit_16")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 340, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_5.setObjectName("label_5")
        self.textEdit_18 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_18.setGeometry(QtCore.QRect(260, 370, 200, 40))
        self.textEdit_18.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_18.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_18.setLineWidth(1)
        self.textEdit_18.setAcceptRichText(False)
        self.textEdit_18.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_18.setObjectName("textEdit_18")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(160, 250, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_16.setObjectName("label_16")
        self.textEdit_19 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_19.setGeometry(QtCore.QRect(210, 250, 250, 40))
        self.textEdit_19.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_19.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_19.setLineWidth(1)
        self.textEdit_19.setAcceptRichText(False)
        self.textEdit_19.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_19.setObjectName("textEdit_19")
        self.textEdit_20 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_20.setGeometry(QtCore.QRect(210, 300, 250, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        self.textEdit_20.setFont(font)
        self.textEdit_20.setStyleSheet("QTextEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}")
        self.textEdit_20.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_20.setLineWidth(1)
        self.textEdit_20.setAcceptRichText(False)
        self.textEdit_20.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_20.setObjectName("textEdit_20")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(160, 300, 70, 40))
        self.label_17.setMaximumSize(QtCore.QSize(1548, 753))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_17.setObjectName("label_17")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 420, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_6.setObjectName("label_6")
        self.textEdit_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_21.setGeometry(QtCore.QRect(260, 450, 200, 40))
        self.textEdit_21.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_21.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_21.setLineWidth(1)
        self.textEdit_21.setAcceptRichText(False)
        self.textEdit_21.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_21.setObjectName("textEdit_21")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(0, 600, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_14.setObjectName("label_14")
        self.textEdit_17 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_17.setGeometry(QtCore.QRect(80, 600, 170, 40))
        self.textEdit_17.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_17.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_17.setLineWidth(1)
        self.textEdit_17.setAcceptRichText(False)
        self.textEdit_17.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_17.setObjectName("textEdit_17")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 500, 141, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel\n"
"{\n"
"    font-family:Microsoft Yahei UI;\n"
"    font-size:16px; \n"
"    font-weight: bold;\n"
"    color:rgb(128, 134, 132)\n"
"}")
        self.label_7.setObjectName("label_7")
        self.textEdit_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_22.setGeometry(QtCore.QRect(260, 530, 200, 40))
        self.textEdit_22.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:15px;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_22.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_22.setLineWidth(1)
        self.textEdit_22.setAcceptRichText(False)
        self.textEdit_22.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_22.setObjectName("textEdit_22")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 620, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:17px;\n"
"    /*字体颜色为白色*/\n"
"    font-weight: bold;    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#C1272D;\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#9e1e24;\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#CD5257;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.calendarWidget.raise_()
        self.label_13.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_3.raise_()
        self.label_11.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.tableWidget_3.raise_()
        self.label_8.raise_()
        self.textEdit_10.raise_()
        self.label_9.raise_()
        self.textEdit_11.raise_()
        self.textEdit_12.raise_()
        self.textEdit_13.raise_()
        self.textEdit_14.raise_()
        self.textEdit_15.raise_()
        self.textEdit_16.raise_()
        self.label_5.raise_()
        self.textEdit_18.raise_()
        self.label_16.raise_()
        self.textEdit_19.raise_()
        self.textEdit_20.raise_()
        self.label_17.raise_()
        self.label_6.raise_()
        self.textEdit_21.raise_()
        self.label_14.raise_()
        self.textEdit_17.raise_()
        self.label_7.raise_()
        self.textEdit_22.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        ClockReview.setCentralWidget(self.centralwidget)

        self.retranslateUi(ClockReview)
        QtCore.QMetaObject.connectSlotsByName(ClockReview)

    def retranslateUi(self, ClockReview):
        _translate = QtCore.QCoreApplication.translate
        ClockReview.setWindowTitle(_translate("ClockReview", "Clock In & Out Review"))
        self.label_13.setText(_translate("ClockReview", "In-2"))
        self.label_10.setText(_translate("ClockReview", "Out-1"))
        self.label_12.setText(_translate("ClockReview", "Out-2"))
        self.label_3.setText(_translate("ClockReview", "Clock In"))
        self.pushButton_2.setText(_translate("ClockReview", "Back"))
        self.label_11.setText(_translate("ClockReview", "In-1"))
        self.pushButton.setText(_translate("ClockReview", "Export Selected Day Record"))
        self.label_2.setText(_translate("ClockReview", "  Please select the date to review"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("ClockReview", "Staff ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("ClockReview", "Staff Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("ClockReview", "Division"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("ClockReview", "Clock In"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("ClockReview", "Cock Out"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("ClockReview", "Out-1"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("ClockReview", "In-1"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("ClockReview", "Out-2"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("ClockReview", "In-2"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("ClockReview", "Work Time"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("ClockReview", "Over Time"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("ClockReview", "Approved OT"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("ClockReview", "Email"))
        self.label_8.setText(_translate("ClockReview", "Staff ID"))
        self.textEdit_10.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_9.setText(_translate("ClockReview", "Division"))
        self.textEdit_11.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:15px;\">-</span></p></body></html>"))
        self.textEdit_12.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_13.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_14.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_15.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_16.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("ClockReview", "Work Time"))
        self.textEdit_18.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_16.setText(_translate("ClockReview", "Name"))
        self.textEdit_19.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_20.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11px;\">-</span></p></body></html>"))
        self.label_17.setText(_translate("ClockReview", "Email"))
        self.label_6.setText(_translate("ClockReview", "Over Time"))
        self.textEdit_21.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_14.setText(_translate("ClockReview", "Clock Out"))
        self.textEdit_17.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_7.setText(_translate("ClockReview", "Approved OT"))
        self.textEdit_22.setHtml(_translate("ClockReview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft Yahei\'; font-size:15px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_3.setText(_translate("ClockReview", "Export Selected Month Record"))
